// <auto-generated />
using Api_Vendas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Vendas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api_Vendas.Models.Item", b =>
                {
                    b.Property<string>("CodItem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("CodItem");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Api_Vendas.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("ItemSale", b =>
                {
                    b.Property<string>("ItemsCodItem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SalesId")
                        .HasColumnType("int");

                    b.HasKey("ItemsCodItem", "SalesId");

                    b.HasIndex("SalesId");

                    b.ToTable("ItemSale");
                });

            modelBuilder.Entity("ItemSale", b =>
                {
                    b.HasOne("Api_Vendas.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsCodItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_Vendas.Models.Sale", null)
                        .WithMany()
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
